name: CI
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # required to pull GitHub releases
          release: latest                       # or: nightly
      - run: odin check . -vet -strict-style