name: Release
on:
  push:
    tags: ['v*']

permissions:
  contents: write          # needed to create the release

jobs:
  check-odin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # required to pull GitHub releases
          release: latest                       # or: nightly
      - run: odin check game -vet -strict-style -collection:http=game/libs/odin-http

  release-odin:
    needs: check-odin
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            out: land-invaders-linux
          - os: windows-latest
            out: land-invaders.exe
          - os: macos-latest
            out: land-invaders-macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y
          libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev
          libxcursor-dev libxi-dev libxext-dev

      - run: odin build game -out:${{ matrix.out }} -o:speed -collection:http=game/libs/odin-http

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.out }}

  check-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26.3"
      - run: go vet ./...
      - run: go test ./...

  build-go-image:
      needs: check-go
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4

        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - uses: docker/build-push-action@v6
          with:
            push: true
            build-args: |
              VERSION=${{ github.ref_name }}
            tags: |
              ghcr.io/maximebonnin/land-invader:latest
              ghcr.io/maximebonnin/land-invader:${{ github.ref_name }}